### ISSUE TITLE
Save to currently does not work

### ISSUE THREAD

**Issue by ZuranaSuki** [Metalloriff/BetterDiscordPlugins#106]
As the title suggest the plugin no longer functions

**Comment by penitencex** [comment]
Yeah its a shame, I wish it did, I used it so much and now I don't have a plugin to download things from discord

**Comment by l0c4lh057** [comment]
Someone else made [an alternative](https://_lighty_.gitlab.io/bdstuff/?plugin=SaveTo)

**Comment by ZuranaSuki** [comment]
I only get plugins that are from the plugin repo plus I don't use plugins made by people who make message loggers not cool.

**Comment by l0c4lh057** [comment]
> I don't use plugins made by people who make message loggers

then you should not even use metalloriff's save to (or any of his other plugins)

**Comment by ZuranaSuki** [comment]
consider them all removed from my pc :)

**Comment by l0c4lh057** [comment]
that's ok, i mean they dont even work anymore. and when you dont want to use plugins you might think are useful and would like to use, just because the author made something you dont like, that is up to you. nobody will even notice, there is no counter for how many people are using a plugin. nobody knows if one person or ten million people use a plugin.

**Comment by ZuranaSuki** [comment]
I want to apologize for my behavior I've been going through a lot lately stress and personal problems but that doesn't excuse my attitude I'm sorry.
