### ISSUE TITLE
Separate GuildAndFriendRemovalAlerts storage for main/ptb/canary or per-account

### ISSUE THREAD

**Issue by TheRedDev** [Metalloriff/BetterDiscordPlugins#225]
Is it possible to store separate sets of guilds/friends for each client type or on a per-account basis? If I use Canary and my kids use Main and PTB respectively, we get removal alerts for each other's friends.

**Comment by Metalloriff** [comment]
I could add this. You're talking about just the release channel (stable, ptb, canary) and not the user itself, correct?

**Comment by TheRedDev** [comment]
Either would solve the problem for my needs.

**Comment by Metalloriff** [comment]
It's a lazy update, and unofficial right now because the compiler I was using isn't working right now, so I had to just edit the minified code. I'll push this to an actual update at some point.

It's in a zip because for some reason you can't upload a JS file directly, and I didn't want you to have to copy paste the code. You should be able to just take the file out of this zip and replace the current one.

[GuildAndFriendRemovalAlerts.plugin.js.zip](https://github.com/Metalloriff/BetterDiscordPlugins/files/7150696/GuildAndFriendRemovalAlerts.plugin.js.zip)
