### ISSUE TITLE
View avatar icon  not working

### ISSUE THREAD

**Issue by ChewyToes** [Metalloriff/BetterDiscordPlugins#237]
i cant view any profile avatar icon since yesterday, i reinstalled everything and again copy pasted the plugin , still cant view avatar
i can just copy the avatar icon link

**Comment by whiteboo** [comment]
Same issue here. The ability to right click for context menu is gone as well. You can make it show up again if you disable and enable the plugin but clicking View Avatar does nothing as well.

**Comment by Metalloriff** [comment]
Thank you for reporting, I'm working on a fix now.

**Comment by Metalloriff** [comment]
I released a really bad patch for it. I have no idea what Discord did to demolish their platform, but it's bad, and I don't feel like spending days figuring it out currently.

All of this is temporary, but this fix will open images in the browser instead of in an image modal, because Discord absolutely demolished their modals system. Also, the context menus won't show until the second time opening them.

I have literally no idea what dumb shit they did to cause all of this, but dumb shit must be fixed with dumb shit, at least currently.
